name: Auto assign owner when opening PRs
on:
  pull_request:
    types: [ opened ]
jobs:
  auto-assign-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign owner
        uses: toshimaru/auto-author-assign@v3.0.2
